#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-archetype
Version  : 3.1.2
Release  : 1
URL      : https://github.com/apache/maven-archetype/archive/maven-archetype-3.1.2.tar.gz
Source0  : https://github.com/apache/maven-archetype/archive/maven-archetype-3.1.2.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-catalog/2.2/archetype-catalog-2.2.jar
Source2  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-catalog/2.2/archetype-catalog-2.2.pom
Source3  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-common/2.2/archetype-common-2.2.jar
Source4  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-common/2.2/archetype-common-2.2.pom
Source5  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-descriptor/2.2/archetype-descriptor-2.2.jar
Source6  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-descriptor/2.2/archetype-descriptor-2.2.pom
Source7  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-models/2.2/archetype-models-2.2.pom
Source8  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-packaging/2.2/archetype-packaging-2.2.jar
Source9  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-packaging/2.2/archetype-packaging-2.2.pom
Source10  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-registry/2.2/archetype-registry-2.2.jar
Source11  : https://repo1.maven.org/maven2/org/apache/maven/archetype/archetype-registry/2.2/archetype-registry-2.2.pom
Source12  : https://repo1.maven.org/maven2/org/apache/maven/archetype/maven-archetype/2.2/maven-archetype-2.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-archetype-data = %{version}-%{release}

%description
Maven Archetype
http://maven.apache.org/archetype/
Developers list: dev@maven.apache.org

%package data
Summary: data components for the mvn-archetype package.
Group: Data

%description data
data components for the mvn-archetype package.


%prep
%setup -q -n maven-archetype-maven-archetype-3.1.2

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-catalog/2.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-catalog/2.2/archetype-catalog-2.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-catalog/2.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-catalog/2.2/archetype-catalog-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-common/2.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-common/2.2/archetype-common-2.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-common/2.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-common/2.2/archetype-common-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-descriptor/2.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-descriptor/2.2/archetype-descriptor-2.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-descriptor/2.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-descriptor/2.2/archetype-descriptor-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-models/2.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-models/2.2/archetype-models-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-packaging/2.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-packaging/2.2/archetype-packaging-2.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-packaging/2.2
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-packaging/2.2/archetype-packaging-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-registry/2.2
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-registry/2.2/archetype-registry-2.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-registry/2.2
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-registry/2.2/archetype-registry-2.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/maven-archetype/2.2
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/archetype/maven-archetype/2.2/maven-archetype-2.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-catalog/2.2/archetype-catalog-2.2.jar
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-catalog/2.2/archetype-catalog-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-common/2.2/archetype-common-2.2.jar
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-common/2.2/archetype-common-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-descriptor/2.2/archetype-descriptor-2.2.jar
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-descriptor/2.2/archetype-descriptor-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-models/2.2/archetype-models-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-packaging/2.2/archetype-packaging-2.2.jar
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-packaging/2.2/archetype-packaging-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-registry/2.2/archetype-registry-2.2.jar
/usr/share/java/.m2/repository/org/apache/maven/archetype/archetype-registry/2.2/archetype-registry-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/archetype/maven-archetype/2.2/maven-archetype-2.2.pom
